name: Formatting Check
on: [push, pull_request]
jobs:
  cxx-format:
    name: Cxx Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 13
          check-path: src

  lua-format:
    name: Lua Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run stylua check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0
          args: --check spec
