name: Formatting Check
on: [push, pull_request]
jobs:
  cxx-format:
    name: Cxx Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format check
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: 13
          check-path: src

  lua-format:
    name: Lua Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.15.1
          args: --check spec
